### ISSUE TITLE
Doesn't run in .scss files

### ISSUE THREAD

**Issue by hugomrdias** [csscomb/sublime-csscomb#18]
Is this by design ?

**Comment by Liquir-ice** [comment]
This solution fix my problem.

```
# Check is installed nodejs or not
$ node -v
v7.1.0
$ which node
/usr/local/bin/node
# Change the node-path in sublime csscomb setting
{
  "node-path" : ":/usr/local/bin"
}
```

Install sass/scss package in sublime

Set current file syntax to scss type in sublime
Sublime Toolbar->view->syntax->scss

Press <kbd>ctrl</kbd>+<kbd>shift</kbd> +<kbd>c</kbd> to run "CSScomb"
