### ISSUE TITLE
Not using config if CSS file not saved

### ISSUE THREAD

**Issue by hudochenkov** [csscomb/sublime-csscomb#23]
If create new tab in ST3 and not save file on disk, then try to sort CSS in this tab — CSSComb will ignore `~/.csscomb.json` and sort with default config. But if `/Users/aleks/Library/Application Support/Sublime Text 3/Packages/User/CSScomb JS.sublime-settings` has option `"custom_config_path": "/Users/aleks/.csscomb.json"` it's work fine. (BTW, `"custom_config_path": "~/.csscomb.json"` throw error.)

v2014.07.23.01.35.56

**Comment by tonyganch** [comment]
The issue should be fixed in `1.2.0`
