### ISSUE TITLE
CSSComb работает не на той конфигурации

### ISSUE THREAD

**Issue by Dimusyan** [csscomb/sublime-csscomb#40]
В Sublime Text 3 установил CSSComb, всё работало нормально. Потом решил поиграться с конфигурацией и что-то пошло не так — оптимальный вариант расчёски оказался сбит. Удалил все файлы конфигураций, которые нашел, переустановил — ничего не помогает. В папку /home/ кладу разные csscomb.json — всё равно причёсывает одним вариантом.

**Comment by tonyganch** [comment]
Проблемы с файлами настроек должны были поправиться в `1.2.0`
