### ISSUE TITLE
Ошибка при media переменных

### ISSUE THREAD

**Issue by uradvd85** [csscomb/sublime-csscomb#44]
![screen shot 2014-11-04 at 13 53 09](https://cloud.githubusercontent.com/assets/3129672/4898487/f87477fc-6410-11e4-904f-7beb27ee1fde.png)

**Comment by uradvd85** [comment]
//Media Queries
@320: ~"screen and (min-width: 320px) and (max-width: 460px)";
@480: ~"only screen and (min-width: 461px) and (max-width: 767px)";
@756: ~"only screen and (min-width: 768px) and (max-width: 991px)";
@1024: ~"only screen and (min-width: 992px) and (max-width: 1199px)";
@1240: ~"only screen and (min-width: 1200px) and (max-width: 1599px)";
@1600: ~"only screen and (min-width: 1600px)";

**Comment by chernetsov0** [comment]
@uradvd85 это всё же важная деталь. Нигде не видел, чтобы **CSScomb** декларировал поддержку **LESS** или **SASS**.

**P.S**.: Судя по блоку, проблема не в переменных а во вложенных *media query*. Потому что, **CSScomb** по сути не должен интересоваться как озаглавлен блок, но вот поддержки вложенных блоков - нет.
