### ISSUE TITLE
csscomb not working for .scss files

### ISSUE THREAD

**Issue by entozoon** [csscomb/sublime-csscomb#7]
I've installed csscomb js into sublime 3 and ctrl+shift+c (or tools>run csscomb js) works fine for .css files but seemingly does nothing (and no console message) within an .scss file.

I know it should work fine with sass because I've used the previous versions with no problems.
It's as if the package only loads for .css files and not others. I wouldn't mind if it loaded for every file type.

Thanks in advance.

**Comment by dimaip** [comment]
@felipeduardo had the same issue, the problem is with weird defaults, should be: `"space-before-opening-brace": " ",`

**Comment by glencampbell** [comment]
Bump! I miss CSS Comb :-(

**Comment by abacaj** [comment]
bump.

**Comment by adonaicandido** [comment]
bump

**Comment by ixley** [comment]
+1

**Comment by ixley** [comment]
I'm not sure if this was it, but building out my config file with explicit sort order seemed to fix things for me. I'm guessing that relying on the default settings for this just wasn't working with sass/scss.

**Comment by ixley** [comment]
I've now gotten it to process most of my scss files fine, but it's throwing an error ("Please check the validity...") for this:
```sass
@for $i from 0 through 2 {
  .pie-slice._#{$i} path, 
  .dc-legend .dc-legend-item:nth-child(#{$i + 1}) rect 
    fill: darken($teal, $i * 10);
  }
}
```
It appears to be choking on interpolating `#{$i + 1}` – so if I remove the `+1` it will complete without errors, but I'm not sure what it doesn't like about this, since it seems to deal with this sort of interpolation fine in other places.

**Comment by gangsthub** [comment]
@ixley, I think you were missing a braket there:

```scss
@for $i from 0 through 2 {
  .pie-slice._#{$i} .path,
  .dc-legend .dc-legend-item:nth-child(#{$i + 1}) rect *{*
    	fill: darken($teal, $i * 10);
  }
}
```

**Comment by ixley** [comment]
@gangsthub Thanks for catching that –I'm not sure why that bracket didn't get pasted in above (I've updated the snippet in my comment), but it is correctly formed and not the cause of the error. Like I mentioned, it appears to not like something about that specific interpolation string with the +1.

**Comment by vohaha** [comment]
font: 400 #{$base-font-size + 3px}/#{$base-btn-line-height} $base-font-family;
The same error: "Please check the validity of the block starting from line #10"

**Comment by rbelling** [comment]
having the same problem here... gonzales is failing while parsing the interpolated valuse in this snippet: 

	$diff-size: strip-unit($max-size - $min-size); //e.g. 13
	$diff-range: $upper-range - $lower-range;
	#{$property}: calc(#{$min-size} + #{$diff-size} * ((100vw - #{$lower-range}px) / #{$diff-range}));

	@include width-under($lower-range) {
		#{$property}: $min-size;
	}
	@include width-over($upper-range) {
		#{$property}: $max-size;
	}

**Comment by arvi** [comment]
I had the same issue. What worked for me is installing SCSS Sublime Package before running csscomb.

**Comment by klierik** [comment]
Have the same problem:

```
Parsing error: Please check the validity of the block starting from line #28

26 |         position: absolute;
27 |         z-index: -100;
28*|         left: calc(50% - #{$loader__loader-circle-size / 2});
29 |         top: calc(50% - #{$loader__loader-circle-size / 2});
```
