### ISSUE TITLE
Update to CSSComb 4.0

### ISSUE THREAD

**Issue by 1337LutZ** [csscomb/sublime-csscomb#83]
Since this plugin has not been updated for a while I was wondering if there will be a version 4.0 support?

Right now I can't seem to add new lines after each ruleset with version 3.0.

```
.a{
  color:red
}

.b{
  color:blue
}
```

will comb to:
```
.a{
  color:red
}
.b{
  color:blue
}
```

If I'm doing something wrong please let me know.

**Comment by loringdodge** [comment]
@1337LutZ This sublime package now uses CSScomb 4.2.0. Feel free to reinstall.
